name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest
  steps:
    - name: "Init repository"
      uses: actions/checkout@v2

    - name: "Setup Node"
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: "Install node"
      run: npm install

    - name: "Build app"
      run: npm run build
